---
trigger:
  - develop

stages:
  - stage: buildimage
    displayName: Build docker image and push
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: buildnpush
        displayName: Build and push docker image
        steps:
          - task: Docker@2
            inputs:
              Dockerfile: "./Dockerfile"
              command: buildAndPush
              tags: latest
              containerRegistry: MyDockerHub
              repository: shaikkhajaibrahim/nopforworkshopmar24
  - stage: deployment
    displayName: Create k8s and deploy
    pool: default
    jobs:
      - job: deploy
        displayName: provision k8s cluster and deploy
        steps:
          - task: Bash@3
            inputs:
              targetType: inline
              workingDirectory: "./Deployments/terraform"
              script: "terraform init && terraform apply -auto-approve"
          - task: Bash@3
            inputs:
              targetType: inline
              script: "kubectl apply -f ./Deployments/k8s"
